version: '3.9'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qwen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    # command: >
    #   sh -c "ollama serve & sleep 5 && ollama pull qwen3.5:9b && wait"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # gpus: all
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        limits:
          memory: 20gb        # The "Hard Limit" - Docker will kill the container if it exceeds this
        reservations:
          memory: 8gb         # The "Soft Limit" - Docker tries to guarantee at least this much
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
    restart: unless-stopped

  flask:
    build: ./backend-flask
    volumes:
      - ./backend-flask:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - ollama
    environment:
      # - http_proxy=http://192.168.0.107:9910
      # - https_proxy=http://192.168.0.107:9910
      # - HTTP_PROXY=http://192.168.0.107:9910
      # - HTTPS_PROXY=http://192.168.0.107:9910
      # - NO_PROXY=localhost,127.0.0.1,ollama,postgres,flask,node
      - HF_ENDPOINT=https://hf-mirror.com
      - JWT_SECRET=super-secret-key-change-this-to-very-long-random-string-123456

  node:
    build: ./backend-node
    volumes:
      - ./backend-node:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - flask

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - node

volumes:
  pgdata:
  ollama_data: